//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articles()
        {
            this.Articles_Comment = new HashSet<Articles_Comment>();
        }
    
        public int art_id { get; set; }
        public int mana_id { get; set; }
        public string art_name { get; set; }
        public string art_image { get; set; }
        public string art_mess { get; set; }
        public Nullable<System.DateTime> art_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articles_Comment> Articles_Comment { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
