//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Keep
    {
        public int lk_id { get; set; }
        public int user_id { get; set; }
        public int list_id { get; set; }
        public Nullable<System.DateTime> lk_time { get; set; }
    
        public virtual List List { get; set; }
        public virtual Users Users { get; set; }
    }
}
