//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music1()
        {
            this.List_Music_Keep = new HashSet<List_Music_Keep>();
            this.Music_Comment = new HashSet<Music_Comment>();
        }
    
        public int music_id { get; set; }
        public string music_music { get; set; }
        public int mana_id { get; set; }
        public string music_name { get; set; }
        public string music_mess { get; set; }
        public string music_image { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<System.DateTime> music_time { get; set; }
        public Nullable<int> point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_Music_Keep> List_Music_Keep { get; set; }
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Music_Comment> Music_Comment { get; set; }
        public virtual Music_Type Music_Type { get; set; }
    }
}
