//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class musicEntities : DbContext
    {
        public musicEntities()
            : base("name=musicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<Articles_Comment> Articles_Comment { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<List_Comment> List_Comment { get; set; }
        public virtual DbSet<List_Keep> List_Keep { get; set; }
        public virtual DbSet<List_Music_Keep> List_Music_Keep { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Music_Comment> Music_Comment { get; set; }
        public virtual DbSet<Music_Type> Music_Type { get; set; }
        public virtual DbSet<Music1> Music1 { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
